export const fetchWeatherKey = Symbol('fetchWeather');
export var WeatherCode;
(function (WeatherCode) {
    WeatherCode[WeatherCode["CLEAR_SKY"] = 0] = "CLEAR_SKY";
    WeatherCode[WeatherCode["MAINLY_CLEAR"] = 1] = "MAINLY_CLEAR";
    WeatherCode[WeatherCode["PARTLY_CLOUDY"] = 2] = "PARTLY_CLOUDY";
    WeatherCode[WeatherCode["OVERCAST"] = 3] = "OVERCAST";
    WeatherCode[WeatherCode["FOG"] = 45] = "FOG";
    WeatherCode[WeatherCode["DEPOSITING_RIME_FOG"] = 48] = "DEPOSITING_RIME_FOG";
    WeatherCode[WeatherCode["DRIZZLE_LIGHT"] = 51] = "DRIZZLE_LIGHT";
    WeatherCode[WeatherCode["DRIZZLE_MODERATE"] = 53] = "DRIZZLE_MODERATE";
    WeatherCode[WeatherCode["DRIZZLE_DENSE"] = 55] = "DRIZZLE_DENSE";
    WeatherCode[WeatherCode["FREEZING_DRIZZLE_LIGHT"] = 56] = "FREEZING_DRIZZLE_LIGHT";
    WeatherCode[WeatherCode["FREEZING_DRIZZLE_DENSE"] = 57] = "FREEZING_DRIZZLE_DENSE";
    WeatherCode[WeatherCode["RAIN_SLIGHT"] = 61] = "RAIN_SLIGHT";
    WeatherCode[WeatherCode["RAIN_MODERATE"] = 63] = "RAIN_MODERATE";
    WeatherCode[WeatherCode["RAIN_HEAVY"] = 65] = "RAIN_HEAVY";
    WeatherCode[WeatherCode["FREEZING_RAIN_LIGHT"] = 66] = "FREEZING_RAIN_LIGHT";
    WeatherCode[WeatherCode["FREEZING_RAIN_HEAVY"] = 67] = "FREEZING_RAIN_HEAVY";
    WeatherCode[WeatherCode["SNOW_FALL_SLIGHT"] = 71] = "SNOW_FALL_SLIGHT";
    WeatherCode[WeatherCode["SNOW_FALL_MODERATE"] = 73] = "SNOW_FALL_MODERATE";
    WeatherCode[WeatherCode["SNOW_FALL_HEAVY"] = 75] = "SNOW_FALL_HEAVY";
    WeatherCode[WeatherCode["SNOW_GRAINS"] = 77] = "SNOW_GRAINS";
    WeatherCode[WeatherCode["RAIN_SHOWERS_SLIGHT"] = 80] = "RAIN_SHOWERS_SLIGHT";
    WeatherCode[WeatherCode["RAIN_SHOWERS_MODERATE"] = 81] = "RAIN_SHOWERS_MODERATE";
    WeatherCode[WeatherCode["RAIN_SHOWERS_VIOLENT"] = 82] = "RAIN_SHOWERS_VIOLENT";
    WeatherCode[WeatherCode["SNOW_SHOWERS_SLIGHT"] = 85] = "SNOW_SHOWERS_SLIGHT";
    WeatherCode[WeatherCode["SNOW_SHOWERS_HEAVY"] = 86] = "SNOW_SHOWERS_HEAVY";
    WeatherCode[WeatherCode["THUNDERSTORM_SLIGHT"] = 95] = "THUNDERSTORM_SLIGHT";
    WeatherCode[WeatherCode["THUNDERSTORM_WITH_HAIL_SLIGHT"] = 96] = "THUNDERSTORM_WITH_HAIL_SLIGHT";
    WeatherCode[WeatherCode["THUNDERSTORM_WITH_HAIL_HEAVY"] = 99] = "THUNDERSTORM_WITH_HAIL_HEAVY";
})(WeatherCode || (WeatherCode = {}));
export var WeatherTimeType;
(function (WeatherTimeType) {
    WeatherTimeType["HOURLY"] = "hourly";
    WeatherTimeType["DAILY"] = "daily";
    WeatherTimeType["CURRENT"] = "current";
})(WeatherTimeType || (WeatherTimeType = {}));
